In [1]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
train_size = 100

In [3]:
def get_top3_per_d(filepath, group_cols):
    """
    Reads an ablation CSV file, aggregates across seeds, 
    and returns the top 3 configs per d.

    Parameters
    ----------
    filepath : str
        Path to the ablation CSV file.
    group_cols : list
        List of columns to group by (must include 'd' and 'method').

    Returns
    -------
    pd.DataFrame
        Top 3 configs per d (sorted by avg_rmse).
    """
    df = pd.read_csv(filepath)

    agg_results = (
        df.groupby(group_cols, as_index=False)
          .agg(avg_rmse=('rmse', 'mean'),
               avg_mae=('mae', 'mean'))
    )

    top3_per_d = (
        agg_results.sort_values(['d', 'avg_rmse'])
                   .groupby('d', group_keys=False)
                   .head(3)
                   .reset_index(drop=True)
    )
    return top3_per_d

In [4]:
top3_xgb = get_top3_per_d(f'results/xgboost_ablation_{train_size}.csv',
                          group_cols=['d', 'method', 'v', 'target_tree_size'])
print("Top 3 configs per d for XGBoost:")
top3_xgb_notransfer = top3_xgb[top3_xgb['method'] == 'xgboost']
top3_xgb_notransfer

Top 3 configs per d for XGBoost:

   d   method     v  target_tree_size  avg_rmse   avg_mae
2  4  xgboost  0.03                 1  1.702366  1.373256

In [5]:
top3_xgb = get_top3_per_d(f'results/xgboost_ablation_{train_size}.csv',
                          group_cols=['d', 'method', 'v', 'target_tree_size'])
print("Top 3 configs per d for XGBoost Naive Transfer:")
top3_xgb_notransfer = top3_xgb[top3_xgb['method'] == 'xgboost_naive_transfer']
top3_xgb_notransfer

Top 3 configs per d for XGBoost Naive Transfer:

   d                  method     v  target_tree_size  avg_rmse   avg_mae
0  4  xgboost_naive_transfer  0.05                 3  1.690230  1.305754
1  4  xgboost_naive_transfer  0.05                 2  1.697172  1.302546

In [6]:
top3_transfer = get_top3_per_d(f'results/LSTransferTreeBoost_ablation_{train_size}.csv',
                               group_cols=['d', 'method', 'v', 'source_tree_size',
                                           'target_tree_size', 'k', 'm_0'])
print("Top 3 configs per d for TransferTreeBoost:")
top3_transfer

Top 3 configs per d for TransferTreeBoost:

,d,method,v,source_tree_size,target_tree_size,k,m_0,avg_rmse,avg_mae
0,4,LSTransferTreeBoost,0.05,1,1,0.01,0.5,1.886805,1.513420
1,4,LSTransferTreeBoost,0.05,1,1,0.05,0.5,1.966375,1.578343

In [7]:
top3_mlp = get_top3_per_d(f'results/MLP_ablation_{train_size}.csv',
                          group_cols=['d', 'method'])
print("Top 3 configs per d for MLP:")
top3_mlp

Top 3 configs per d for MLP:

   d method  avg_rmse  avg_mae
0  4    MLP   2.18218  1.77854